trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md
      - docs/**

pool:
  name: MyFreePool

variables:
  - name: node_version
    value: '18.x'
  - name: SCM_DO_BUILD_DURING_DEPLOYMENT
    value: true

stages:
- stage: Test
  displayName: "Run Tests"
  jobs:
  - job: RunTests
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(node_version)'
      displayName: 'Install Node.js'

    - task: Cache@2
      displayName: 'Cache node_modules'
      inputs:
        key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
        path: '$(Build.SourcesDirectory)/node_modules'
        restoreKeys: |
          npm | "$(Agent.OS)"
      continueOnError: true

    - script: npm ci --no-audit --no-fund
      displayName: 'Install NPM dependencies'

    - script: |
        npm install @playwright/test
        npx playwright install --with-deps
      displayName: 'Install Playwright & Browsers'

    - script: npm test
      displayName: 'Run Unit Tests'
      continueOnError: true

    - script: |
        mkdir -p playwright-report
        npx playwright test --reporter=html
      displayName: 'Run Playwright Tests'
      continueOnError: true

    - task: PublishBuildArtifacts@1
      condition: always()
      displayName: 'Publish Playwright HTML Report'
      inputs:
        pathToPublish: 'playwright-report'
        artifactName: 'playwright-report'
        publishLocation: 'Container'

- stage: Package
  displayName: "Package App"
  dependsOn: Test
  jobs:
  - job: ArchiveAndPublish
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(node_version)'
      displayName: 'Install Node.js'

    - script: npm ci --no-audit --no-fund
      displayName: 'Install NPM dependencies'
      env:
        NODE_ENV: production

    - task: ArchiveFiles@2
      displayName: 'Archive app'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
        artifactName: 'shopingkaro-app'
        publishLocation: 'Container'

- stage: Deploy
  displayName: "Deploy to Azure"
  dependsOn: Package
  condition: succeeded()
  jobs:
  - deployment: DeployToAzureAppService
    displayName: "Deploy Web App"
    environment: deployappr
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download build artifact"
            inputs:
              artifactName: "shopingkaro-app"
              downloadPath: "$(Pipeline.Workspace)"

          - task: AzureWebApp@1
            displayName: "Deploy to Azure Web App"
            inputs:
              azureSubscription: "azure-rm-shopingkaro"
              appType: "webApp"
              appName: "shopingkaro-app-service"
              package: "$(Pipeline.Workspace)/shopingkaro-app/shopingkaro.zip"