trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md
      - docs/**

pool:
  name: MyFreePool


variables:
  - name: node_version
    value: '18.x'

stages:
# 1. Install Stage
- stage: Install
  displayName: "Install Dependencies"
  jobs:
    - job: InstallNode
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '$(node_version)'
          displayName: 'Install Node.js'
        - task: CmdLine@2
          displayName: 'Install NPM dependencies'
          inputs:
            script: npm ci --no-audit --no-fund

# 2. Test Stage
- stage: Test
  displayName: "Run Unit and E2E Tests"
  dependsOn:
    - Install
  jobs:
    - job: RunTests
      steps:
        - task: Cache@2
          inputs:
            key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
            restoreKeys: |
              npm | "$(Agent.OS)"
            path: $(Build.SourcesDirectory)/node_modules
          displayName: 'Cache node_modules'
          continueOnError: true

        - task: CmdLine@2
          displayName: 'Run Unit Tests'
          inputs:
            script: npm test

        # ✅ Install Playwright Browsers
        - task: CmdLine@2
          displayName: 'Install Playwright Browsers'
          inputs:
            script: npx playwright install --with-deps

        # ✅ Run Playwright E2E Tests
        - task: CmdLine@2
          displayName: 'Run Playwright E2E Tests'
          inputs:
            script: npx playwright test

        # ✅ Optional: Publish Playwright report as artifact
        - task: PublishBuildArtifacts@1
          condition: always()
          inputs:
            pathToPublish: 'playwright-report'
            artifactName: 'playwright-report'
            publishLocation: 'Container'
          displayName: 'Publish Playwright HTML Report'


# 3. Package Stage
- stage: Package
  displayName: "Package App"
  dependsOn:
    - Test
  jobs:
    - job: ArchiveAndPublish
      steps:
        - task: CmdLine@2
          displayName: 'Build step (Optional)'
          inputs:
            script: echo "No build step needed for Express"
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
            replaceExistingArchive: true
          displayName: 'Archive app'
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
            artifactName: 'shopingkaro-app'
            publishLocation: 'Container'
          displayName: 'Publish artifact'

# 4. Release Approval Stage
- stage: Release
  displayName: "Release Approval Stage"
  dependsOn:
    - Package
  condition: succeeded()
  jobs:
    - deployment: NotifyRelease
      displayName: "Release Confirmation"
      environment:
        name: Release
      strategy:
        runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                displayName: 'Release Confirmation'
                inputs:
                  script: echo " Application ready for production deployment."

# 5. Deploy Stage
- stage: Deploy
  displayName: "Deploy to Azure"
  dependsOn:
    - Release
  jobs:
    - deployment: DeployToAzureAppService
      displayName: "Deploy Web App"
      environment:
        name: deployappr
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'shopingkaro-app'
                  downloadPath: '$(Pipeline.Workspace)'
                displayName: 'Download build artifact'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'azure-rm-shopingkaro'
                  appType: 'webApp'
                  appName: 'shopingkaro-app-service'
                  package: '$(Pipeline.Workspace)/shopingkaro-app/shopingkaro.zip'
                displayName: 'Deploy to Azure Web App'
