trigger:
- master

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  node_version: '18.x'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '$(node_version)'
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      npm ci --no-audit --no-fund
    displayName: 'Install dependencies'

  # Cache node_modules (after install to ensure folder exists)
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Build.SourcesDirectory)/node_modules
    displayName: 'Cache node_modules'
    continueOnError: true

  # Run tests (currently placeholder)
  - script: |
      npm test
    displayName: 'Run tests'

  # Build step (not needed for Express apps, optional placeholder)
  - script: |
      echo "No build step needed for Node.js Express app"
    displayName: 'Build step'
    condition: succeeded()

  # Publish artifact (optional if you want to deploy or share zipped app)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)'
      artifactName: 'shopingkaro-app'
      publishLocation: 'Container'
    condition: succeeded()
    displayName: 'Publish artifact'
