trigger:
- master

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2


steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm ci --no-audit --no-fund
    displayName: 'Install dependencies'

  - script: npm test
    displayName: 'Run tests'
