trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md
      - docs/**

pool:
  name: MyFreePool

variables:
  - name: node_version
    value: '18.x'
  - name: SCM_DO_BUILD_DURING_DEPLOYMENT
    value: true

stages:

# 1. Install Stage
- stage: Install
  displayName: "Install Dependencies"
  jobs:
    - job: InstallNode
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '$(node_version)'
          displayName: 'Install Node.js'

        - script: npm ci --no-audit --no-fund
          displayName: 'Install NPM dependencies'

        - script: npm install --only=dev
          displayName: 'Install Dev Dependencies'

        - script: npx playwright install --with-deps
          displayName: 'Install Playwright Browsers'

# 2. Test Stage
- stage: Test
  displayName: "Run Unit and E2E Tests"
  dependsOn: Install
  jobs:
    - job: RunTests
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '$(node_version)'
          displayName: 'Install Node.js'

        - task: Cache@2
          displayName: 'Cache node_modules'
          inputs:
            key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
            restoreKeys: |
              npm | "$(Agent.OS)"
            path: '$(Build.SourcesDirectory)/node_modules'
          continueOnError: true

        - script: npm ci --no-audit --no-fund
          displayName: 'Install NPM dependencies'

        - script: |
            npm install @playwright/test allure-playwright allure-commandline --save-dev
            npx playwright install --with-deps
          displayName: 'Install Playwright, Allure, and Browsers'

        - script: npm test
          displayName: 'Run Unit Tests'
          continueOnError: true

        - script: |
            mkdir -p playwright-report
            mkdir -p allure-results
            npx playwright test --reporter=html,allure-playwright || echo "Tests failed but reports will still be generated."
          displayName: 'Run Playwright Tests with Reporters'
          continueOnError: true

        - script: |
            npx allure generate allure-results --clean -o allure-report
          displayName: 'Generate Allure Report'
          continueOnError: true

        - task: PublishAllureReport@1
          condition: always()
          displayName: 'Publish Allure Report'
          inputs:
            testResultsDir: 'allure-results'
            reportDir: 'allure-report'
            allureVersion: '2.27.0'

        - task: PublishBuildArtifacts@1
          condition: always()
          displayName: 'Publish Playwright HTML Report'
          inputs:
            pathToPublish: 'playwright-report'
            artifactName: 'playwright-report'
            publishLocation: 'Container'

        - task: PublishBuildArtifacts@1
          condition: always()
          displayName: 'Publish Allure Report Artifact'
          inputs:
            pathToPublish: 'allure-report'
            artifactName: 'allure-report'
            publishLocation: 'Container'

# 3. Package Stage
- stage: Package
  displayName: "Package App"
  dependsOn: Test
  jobs:
    - job: ArchiveAndPublish
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '$(node_version)'
          displayName: 'Install Node.js'

        - script: npm ci --no-audit --no-fund
          displayName: 'Install NPM dependencies'
          env:
            NODE_ENV: production

        - script: |
            IF NOT EXIST node_modules (
              echo Error: node_modules directory not found.
              exit 1
            )
          displayName: 'Verify node_modules'

        - task: ArchiveFiles@2
          displayName: 'Archive App'
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
            replaceExistingArchive: true
            archiveFilePatterns: |
              **/*
              .env
              node_modules/**

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
            artifactName: 'shopingkaro-app'
            publishLocation: 'Container'

# 4. Deploy to DEV
- stage: Deploy_DEV
  displayName: "Deploy to DEV"
  dependsOn: Package
  jobs:
    - deployment: DeployToDev
      displayName: "Deploy to Dev Environment"
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'shopingkaro-app'
                  downloadPath: '$(Pipeline.Workspace)'

              - task: AzureWebApp@1
                displayName: "Deploy to Dev App"
                inputs:
                  azureSubscription: "azure-rm-shopingkaro"
                  appType: "webApp"
                  appName: "shopingkaro-dev"
                  package: "$(Pipeline.Workspace)/shopingkaro-app/shopingkaro.zip"

# 5. Deploy to QA (after manual approval set in environment UI)
- stage: Deploy_QA
  displayName: "Deploy to QA"
  dependsOn: Deploy_DEV
  condition: succeeded()
  jobs:
    - deployment: DeployToQA
      displayName: "Deploy to QA Environment"
      environment: QA  # <-- Approval configured in Azure UI
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'shopingkaro-app'
                  downloadPath: '$(Pipeline.Workspace)'

              - task: AzureWebApp@1
                displayName: "Deploy to QA App"
                inputs:
                  azureSubscription: "azure-rm-shopingkaro"
                  appType: "webApp"
                  appName: "shopingkaro-qa"
                  package: "$(Pipeline.Workspace)/shopingkaro-app/shopingkaro.zip"

# 6. Deploy to PROD (after manual approval set in environment UI)
- stage: Deploy_PROD
  displayName: "Deploy to PROD"
  dependsOn: Deploy_QA
  condition: succeeded()
  jobs:
    - deployment: DeployToProd
      displayName: "Deploy to Prod Environment"
      environment: Prod  # <-- Approval configured in Azure UI
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'shopingkaro-app'
                  downloadPath: '$(Pipeline.Workspace)'

              - task: AzureWebApp@1
                displayName: "Deploy to Prod App"
                inputs:
                  azureSubscription: "azure-rm-shopingkaro"
                  appType: "webApp"
                  appName: "shopingkaro-app-service"
                  package: "$(Pipeline.Workspace)/shopingkaro-app/shopingkaro.zip"
