trigger:
- master

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  node_version: '18.x'
  deploy_port: '4000'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(node_version)'
    displayName: 'Install Node.js'

  - script: |
      npm ci --no-audit --no-fund
    displayName: 'Install dependencies'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Build.SourcesDirectory)/node_modules
    displayName: 'Cache node_modules'
    continueOnError: true

  - script: npm test
    displayName: 'Run tests'

  - script: echo "No build step needed for Express"
    displayName: 'Build step'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
      replaceExistingArchive: true
    displayName: 'Archive app'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
      artifactName: 'shopingkaro-app'
      publishLocation: 'Container'
    displayName: 'Publish artifact'

  # 🔥 Actual Azure Web App Deployment Task
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-rm-shopingkaro'  # ✅ The new service connection
      appType: 'webApp'
      appName: 'shopingkaro-app-service'         # ✅ Your Azure Web App name
      package: '$(Build.ArtifactStagingDirectory)/shopingkaro.zip'
    displayName: 'Deploy to Azure Web App'
